name: Plots family trees
on: [push]
jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rstacruz/kingraph
        run: npm install -g rstacruz/kingraph
      - name: Plot family trees
        run: |
          find . -maxdepth 1 -name "*.yml" -exec kingraph --format=svg {} > temp.svg \; -exec mv temp.svg {}.svg \;
          for file in *.yml.svg; { mv "$file" "${file%%.yml.svg}.svg"; }
          ls -al
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: '**.svg'
      - name: Count changes
        id: changes
        run: |
          git add -N *.txt # 新規ファイルを含める
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update image"
          git push
        if: steps.changes.outputs.count > 0
