name: Plots family trees

on:
  push:
    paths:
      - '**.yml'#すべてのymlを含む
      - '*.yml' #ルートのymlのみ

jobs:
  plot:
    permissions:
      contents: write

    strategy:
      matrix:
        format: [svg] # Available in 3 types: svg, png, dot

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install rstacruz/kingraph
        run: npm install -g rstacruz/kingraph
      - name: Plot family trees
        run: |
          rename="for file in '*.yml.${{ matrix.format }}'; { mv "$file" "${file%%.yml.${{ matrix.format }}}.${{ matrix.format }}"; }"
          echo $rename
          find . -maxdepth 1 -name "*.yml" \
            -exec kingraph --format=${{ matrix.format }} {} > temp.${{ matrix.format }} \; \
            -exec mv temp.${{ matrix.format }} {}.${{ matrix.format }} \; \
            -exec bash -c $rename \;
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: '**.${{ matrix.format }}'
      - name: Check diff
        id: diff
        run: |
          git add -N *.${{ matrix.format }}
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'Update image'
          git push
        if: steps.diff.outcome == 'failure'
