name: Plots family trees
on: [push]
jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rstacruz/kingraph
        run: npm install -g rstacruz/kingraph
      - name: Plot family trees
        run: |
          find . -maxdepth 1 -name "*.yml" -exec kingraph --format=svg {} > {}.svg \;
          ls -alR
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: '**.svg'
