name: Plots family trees
on:
  push:
    paths:
      - '**.yml'#すべてのymlを含む
      - '*.yml' #ルートのymlのみ
jobs:
  plot:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rstacruz/kingraph
        run: npm install -g rstacruz/kingraph
      - name: Plot family trees
        run: |
          find . -maxdepth 1 -name "*.yml" -exec kingraph --format=svg {} > temp.svg \; -exec mv temp.svg {}.svg \;
          for file in *.yml.svg; { mv "$file" "${file%%.yml.svg}.svg"; }
          ls -al
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: '**.svg'
      - name: Check diff
        id: diff
        run: |
          git add -N *.svg
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'Update image'
          git push
        if: steps.diff.outcome == 'failure'
